### ISSUE TITLE
Simple, Standards-based Archiving in Dataverse

### ISSUE THREAD

**Issue by nniiicc** [ResearchObject/ro2019#6]
### Authors

* **Name**: James Myers
* **Affiliation**: SEAD; Qualitative Data Repository (QDR) 

* **Name**: Sebastian Karcher
* **Affiliation**: Qualitative Data Repository (QDR) 

* **Name**: Sebastian Ostrowski
* **Affiliation**: Qualitative Data Repository (QDR) 

* **Name**: Nic Weber 
* **Affiliation**: University of Washington-Seattle; Qualitative Data Repository (QDR) 

### Keywords
* Data Archiving 
* Data Packaging
* FAIR Data 

### Abstract
We describe the development of a tool for archiving packages of research data, metadata, and related documentation.

..

Full PDF: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3384296.svg)](https://doi.org/10.5281/zenodo.3384296)

**Comment by stain** [comment]
Thank you for submitting to RO2019's open peer review process. We will shortly be assigning members from the [Programme Committee](https://researchobject.github.io/ro2019/#program-committee) to review.

Feel free to respond to reviewers comments and to update the submission if needed. 

**Tip:** Anyone is welcome to add an informal review below using GitHub comments; as an author perhaps you would volunteer to review [one of the other open submissions](https://github.com/ResearchObject/ro2019/issues)? 

Reviewers, please copy this review form and add as a comment. You don't need to use this form if you are not assigned from the PC.

```markdown
## Quality of Writing
_Is the text easy to follow? Are core concepts defined or referenced? 
Is it clear what is the author's contribution?_

(delete as appropriate)
* excellent / good / fair / poor

## Research Object / Zenodo

_URL for a Research Object or Zenodo record provided?
   Guidelines <http://researchobject.org/ro2019/submitting> followed?
   Open format (e.g. HTML)?
   Sufficient metadata, e.g. links to software?
   Some form of Data Package provided?
   Add text below if you need to clarify your score._

(delete as appropriate)
* none (e.g. only abstract in easychair/github)
* basic (e.g. Zenodo with PDF and minimal metadata)
* sufficient (e.g. HTML, detailed Zenodo metadata)
* good (followed guidelines, demonstrating own format, related resources included, but some details missing)
* excellent (e.g. followed all guidelines, complete metadata or RO-like research data package, linked data, provenance)

## Overall evaluation
_Please provide a brief review, including a justification for your scores. 
Both score and  review text are required._

(delete as appropriate)
* strong reject
* reject
* weak reject
* borderline 
* weak accept
* accept
* strong accept
```

For confidential remarks or questions about the peer-review process, contact ro2019@easychair.org

**Comment by ptsefton** [comment]
I will review within 24 hours.

**Comment by ptsefton** [comment]
## Quality of Writing


Good 

(but it would be good to make processes clearer by making agency more explicit in some of the processes described instead of " In the current implementation, each version of a Dataset is archived as a single zip file (accompanied by a redundant datacite.xml file to simplify discovery"

I would put it like: "The software archives each version of a Dataset as a single zip file  ..."  (and so for what administrators and programmers and end users do)

## Research Object / Zenodo

URL for a Research Object or Zenodo record provided? 
   Guidelines <http://researchobject.org/ro2019/submitting> followed?
   Open format (e.g. HTML)? NO
   Sufficient metadata, e.g. links to software? NO - Could not find a link to the software
   Some form of Data Package provided? NO - could have had an example by packaging the PDF and source files.
 

(delete as appropriate)
* basic (e.g. Zenodo with PDF and minimal metadata)

## Overall evaluation

This submission describes an additional service for the Dataverse software which
creates archival packages and sends them to a couple of services. I think it
should be made more explicit what sending means? What protocols/methods are used? "QDR
has created classes that send zipped BagIt archive files to DuraCloud (from
which content can then be sent into Chronopolis) or Google’s Cloud Storage
(including the least-expensive ‘cold’ storage)".

This statement is also problematic in that it takes a bit of a shortcut: "They
produce a single archive file per Dataset version that is human and machine
readable, providing a complete copy of research published through Dataverse that
can be preserved using any repository providing file or object (e.g. S3)
storage." The archive files seem to be zip files - which are NOT human readable,
and it's debatable whether OAI-ORE is human readable. I couldn't tell from the
example where I might find the example "Hamilton_ATI Data Overview.pdf" file in
the zip file.

But, those issues aside this looks like a useful contribution to the workshop
and the art of data packaging.


* accept

**Comment by stain** [comment]
I will review

**Comment by stain** [comment]
## Quality of Writing
_Is the text easy to follow? Are core concepts defined or referenced? 
Is it clear what is the author's contribution?_

* good

Some typos in the citations in the PDF - e.g. _"BagIt standards3"_ and _"RDRI recommends4"_ should use "[3]" etc. 

References 1, 2, 5, 6 don't have corresponding inline references which should beinserted.

Figure 1 has placeholder caption "_This is a caption_"

## Research Object / Zenodo

[x] URL for a Research Object or Zenodo record provided?
[x] Guidelines <http://researchobject.org/ro2019/submitting> followed?
[x] Open format (e.g. HTML)?
[ ] Sufficient metadata, e.g. links to software?
[ ]Some form of Data Package provided?

* basic (e.g. Zenodo with PDF and minimal metadata)

As the abstract is quite well structured and has 6 references it would be good if these also appeared as "Related identifiers" in the Zenodo record, or at least was hyperlinks from the PDF.

A link to the Dataverse software would also fit as a Related Identifier.

The Zenodo record do not specify the ORCID identifiers for any of the authors.

## Overall evaluation

* strong accept

This abstract describes how Dataverse has been extended to support RDA data packaging recommendations for archiving along with recommended standards like BagIt. Structured metadata is examplified with the use of OAI-ORE combined with schema.org and other vocabularies.

Beyond checksums the text does not describe much about where the metadata comes from, presumably from Dataverse registration fields? Thoughts on how this could be used or expanded would be interesting, particularly considerations around if Dataverse could import such metadata from uploaded data packages as well (e.g. Dataverse-to-archive-to-Dataverse transfer).

I think this poster would be a strong fit for the RO2019 workshop, in particular for data packaging, infrastructure and metadata. It would be nice if the authors would also be able to demo the software during the unconference session.

**Comment by stain** [comment]
Apologies for the delay, @nniiicc  

We are happy to announce that your poster has been **accepted** for RO2019. 

The informal poster session is in the workshop room during lunch 12:00-13:00, as well as in the "unconference" session - see <https://researchobject.github.io/ro2019/schedule> for the programme. 

We welcome poster presenters to do a lightning talk at the 11:55 slot (~ 2 minutes) - one slide.

We would like to invite you to also do a demo during the unconference session, this can either be short plenary demo on the shared screen (~5 mins), or on your laptop in break-out groups.
